### ISSUE TITLE
Make 0-db a reusable library

### ISSUE THREAD

**Issue by maxux** [threefoldtech/0-db#43]
Right now, 0-db is a single binary code. This code can't be shared, caused by lot of global stuff and internal dependencies.

The idea would make data, index, namespaces, etc. all that stuff inside a library (shared or not) called `libzdb` and `zdb` would become a redis-frontend calling `libzdb` feature.

This will allows tools and any external program to use `0-db` as storage stuff and not absolutely need to run a server to use it.

# Roadmap
- [ ] Remove global variable as much as possible, inside core stuff
- [ ] Move core database code to dedicated directory
- [ ] Update tests to test db core code and frontend
- [ ] Make zdb a redis-frontend calling `libzdb` behind
- [ ] Make 0-db even better
